filetype off

set runtimepath+=vader.vim
set runtimepath+=..

"set tabstop=2                     " a tab is two spaces
"set shiftwidth=2                  " an autoindent (with <<) is two spaces
"set expandtab                     " use spaces, not tabs


filetype plugin on
syntax enable

set hidden

let g:linny_debug = 0
let g:linny_path_dbroot = './linny_db_root'
let g:linny_path_dbindex = './linny_index_files'
let g:linny_path_uistate = './linny_state'
let g:linny_index_cli_command = '/Users/pim/RnD/lindex/bin/lindex make -c ~/.linny_dev.yml'
let g:linny_menu_padding_left = 0
let g:linny_menu_padding_right= 0
